### ISSUE TITLE
Update the contributing guidelines

### ISSUE THREAD

**Issue by AlexITC** [AlexITC/crypto-coin-alerts#28]
The [contributing guidelines](https://github.com/AlexITC/crypto-coin-alerts/blob/develop/CONTRIBUTING.md) could be better.

### Expected behavior

The [contributing guidelines](https://github.com/AlexITC/crypto-coin-alerts/blob/develop/CONTRIBUTING.md) look similar to [these ones](https://github.com/X9Developers/block-explorer/blob/develop/CONTRIBUTING.md) having the hyperlinks and project names updated to our project.

### Actual behavior

The current [contributing guidelines](https://github.com/AlexITC/crypto-coin-alerts/blob/develop/CONTRIBUTING.md) are outdated.

**Comment by danfoy** [comment]
On it
